import { useState } from 'react'
import { Shield, Database, Eye, Users, Lock, AlertTriangle, Mail, FileText } from 'lucide-react'

const Section = ({ icon: Icon, title, children, id }) => (
  <div id={id} className="mb-10">
    <div className="flex items-center gap-3 mb-3 border-b border-gray-200 pb-2">
      <div className="w-8 h-8 bg-brand-600 rounded-lg flex items-center justify-center flex-shrink-0">
        <Icon size={16} className="text-white" />
      </div>
      <h2 className="text-lg font-bold text-gray-900">{title}</h2>
    </div>
    <div className="text-sm text-gray-700 space-y-3 leading-relaxed">{children}</div>
  </div>
)

const Clause = ({ number, title, children }) => (
  <div className="bg-gray-50 border border-gray-200 rounded-lg p-4 mb-3">
    <p className="font-semibold text-gray-800 mb-1">
      <span className="text-brand-600 mr-2">{number}.</span>{title}
    </p>
    <p className="text-gray-600 text-sm leading-relaxed">{children}</p>
  </div>
)

export default function PrivacyPage() {
  const [activeTab, setActiveTab] = useState('privacy')

  return (
    <div className="max-w-3xl mx-auto px-4 py-10">

      {/* Header */}
      <div className="text-center mb-8">
        <div className="w-14 h-14 bg-brand-600 rounded-2xl flex items-center justify-center mx-auto mb-4">
          <Shield size={28} className="text-white" />
        </div>
        <h1 className="text-3xl font-bold text-gray-900 mb-2">Legal & Privacy</h1>
        <p className="text-gray-500 text-sm">
          Hunch — AI-Powered Business Location Platform for Rwanda<br />
          Last updated: July 2026 · Effective: July 2026
        </p>
      </div>

      {/* Tab switcher */}
      <div className="flex gap-2 mb-8 bg-gray-100 p-1 rounded-xl">
        {[
          { key: 'privacy', label: 'Privacy Policy' },
          { key: 'eula',    label: 'End-User Licence Agreement (EULA)' },
        ].map(t => (
          <button key={t.key} onClick={() => setActiveTab(t.key)}
            className={`flex-1 py-2.5 rounded-lg text-sm font-medium transition-colors ${
              activeTab === t.key
                ? 'bg-white text-brand-700 shadow-sm'
                : 'text-gray-500 hover:text-gray-700'
            }`}>
            {t.label}
          </button>
        ))}
      </div>

      {/* ── PRIVACY POLICY ── */}
      {activeTab === 'privacy' && (
        <div>
          <div className="bg-blue-50 border border-blue-200 rounded-xl p-4 mb-8 text-sm text-blue-800">
            <strong>Plain language summary:</strong> Hunch does not collect your name, email, or any personal
            information. It only processes the map coordinates you choose and the business type you select
            in order to generate a location score. No data is sold or shared with third parties.
          </div>

          <Section icon={Database} title="What Data We Collect" id="data-collection">
            <p>Hunch collects only the minimum data necessary to generate a location suitability score. Specifically:</p>
            <ul className="list-disc pl-5 space-y-1 mt-2">
              <li><strong>Location coordinates</strong> (latitude and longitude) — entered by you or detected from your map click</li>
              <li><strong>Business type</strong> — the category you select (e.g. restaurant, pharmacy)</li>
              <li><strong>Prediction outputs</strong> — the score and feature breakdown generated by the ML model</li>
              <li><strong>Query metadata</strong> — timestamp of your request (used for analytics only)</li>
            </ul>
            <p className="mt-3">
              We do <strong>not</strong> collect your name, email address, phone number, IP address, device
              identifier, or any information that would identify you as an individual. Hunch is designed to
              be fully anonymous by default.
            </p>
          </Section>

          <Section icon={Eye} title="How We Use Your Data" id="data-use">
            <p>The data you provide is used solely to:</p>
            <ul className="list-disc pl-5 space-y-1 mt-2">
              <li>Run the Random Forest ML model to generate a suitability score for your chosen location</li>
              <li>Return the score, confidence level, and feature explanations to you in the browser</li>
              <li>Store anonymised query logs in our SQLite database for system performance monitoring</li>
            </ul>
            <p className="mt-3">
              Your data is never used to build individual profiles, target you with advertising, or make any
              automated decisions about you as a person. The predictions Hunch generates are about
              <em> locations</em>, not about individuals.
            </p>
          </Section>

          <Section icon={Lock} title="Data Storage and Security" id="data-storage">
            <p>
              All prediction queries are stored in a SQLite database hosted on Render.com (United States).
              Data is retained for a maximum of 12 months and then deleted. No backup copies are maintained
              beyond this period.
            </p>
            <p>
              Communication between your browser and the Hunch API is encrypted using HTTPS/TLS. The backend
              API requires no authentication, but does not expose any data retrieval endpoints that would
              allow bulk data export by users.
            </p>
            <p>
              Under Rwanda Law N°058/2021 on the Protection of Personal Data and Privacy, and in alignment
              with GDPR Article 5 principles of data minimisation and storage limitation, we have designed
              the system to store only what is necessary for the shortest time necessary.
            </p>
          </Section>

          <Section icon={Users} title="Third-Party Services" id="third-parties">
            <p>Hunch integrates with the following external services:</p>
            <ul className="list-disc pl-5 space-y-2 mt-2">
              <li>
                <strong>Google Places API</strong> — used during model training to collect real business
                location data from Rwanda. Not called during live user sessions. Governed by Google's Terms
                of Service and Privacy Policy.
              </li>
              <li>
                <strong>OpenStreetMap / Overpass API</strong> — used for the Area Analysis feature to retrieve
                landuse information. No user data is transmitted to OSM; only district coordinates are sent.
              </li>
              <li>
                <strong>Render.com</strong> — backend hosting provider. Processes coordinates and business
                type when you make a prediction request. Subject to Render's Privacy Policy.
              </li>
              <li>
                <strong>Vercel</strong> — frontend hosting provider. Serves the web application. Subject to
                Vercel's Privacy Policy.
              </li>
            </ul>
          </Section>

          <Section icon={Shield} title="Your Rights" id="user-rights">
            <p>
              Because Hunch does not collect personally identifiable information, most data subject rights
              under Rwanda Law N°058/2021 and GDPR (such as the right to access, rectification, or erasure
              of personal data) do not apply in the traditional sense — there is no personal data linked to
              you that we could retrieve or delete on request.
            </p>
            <p>
              However, if you have specific concerns about data processed in connection with your use of Hunch,
              you may contact us at the address below and we will respond within 30 days.
            </p>
          </Section>

          <Section icon={AlertTriangle} title="Limitations and Disclaimer" id="disclaimer">
            <p>
              Hunch is an informational tool designed to support business location decisions in Rwanda. It is
              not a substitute for professional business, legal, or financial advice. The suitability scores
              generated are based on a machine learning model trained on data available as of 2026 and may
              not reflect current market conditions, regulatory changes, or local knowledge.
            </p>
            <p>
              <strong>Prediction accuracy:</strong> The model achieves an AUC-ROC of 82.7% on test data, meaning
              approximately 17% of predictions may not accurately reflect real-world outcomes. Users should
              treat Hunch scores as one input among many, not as a definitive business recommendation.
            </p>
            <p>
              <strong>Geographic limitation:</strong> Hunch is calibrated for Rwanda only. Predictions for
              locations outside Rwanda are not supported and will produce unreliable results.
            </p>
          </Section>

          <Section icon={Mail} title="Contact" id="contact">
            <p>For privacy-related questions or concerns:</p>
            <ul className="list-disc pl-5 mt-2 space-y-1">
              <li><strong>Project Lead:</strong> Phinah Mahoro</li>
              <li><strong>Institution:</strong> African Leadership University, Kigali, Rwanda</li>
              <li><strong>System:</strong> hunch.vercel.app</li>
              <li><strong>API:</strong> locosense.onrender.com</li>
            </ul>
          </Section>
        </div>
      )}

      {/* ── EULA ── */}
      {activeTab === 'eula' && (
        <div>
          <div className="bg-amber-50 border border-amber-200 rounded-xl p-4 mb-8 text-sm text-amber-800">
            <strong>Important:</strong> By using Hunch, you agree to the terms below. If you do not agree,
            please do not use the platform. This EULA governs your use of the Hunch web application and API.
          </div>

          <Section icon={FileText} title="End-User Licence Agreement" id="eula-main">

            <Clause number="1" title="Grant of Licence">
              Hunch grants you a free, non-exclusive, non-transferable, revocable licence to access and use
              the Hunch web application (hunch.vercel.app) and its associated API for personal,
              non-commercial, informational purposes only. This licence is provided at no cost and does not
              grant you any ownership rights over the platform, its data, or its machine learning models.
            </Clause>

            <Clause number="2" title="Permitted Use">
              You may use Hunch to: (a) assess the suitability of business locations in Rwanda for
              informational purposes; (b) explore the publicly available training dataset; (c) access the
              API for personal research or educational use. You must not use Hunch to: (a) make
              commercially-binding decisions without independent professional advice; (b) reproduce or
              redistribute the ML model, training data, or system outputs at scale; (c) attempt to reverse
              engineer, scrape, or overload the API.
            </Clause>

            <Clause number="3" title="No Professional Advice">
              Hunch does not provide legal, financial, regulatory, or business consulting advice. The
              location scores and recommendations are generated by a machine learning model and are
              informational only. You are solely responsible for any business decisions you make based on
              Hunch outputs. Hunch, its developers, and African Leadership University accept no liability
              for commercial losses arising from reliance on the platform.
            </Clause>

            <Clause number="4" title="Intellectual Property">
              The Hunch platform, including its source code, trained Random Forest model, system
              architecture, and user interface, is the intellectual property of Phinah Mahoro and African
              Leadership University. The training dataset includes data collected from Google Places API
              (470 real records) and synthetically generated records. Google Places data is used under
              Google's Terms of Service. OpenStreetMap data is used under the Open Database Licence (ODbL).
            </Clause>

            <Clause number="5" title="Data and Privacy">
              Your use of Hunch is subject to the Hunch Privacy Policy (see Privacy Policy tab). By using
              the platform, you confirm that you have read and understood the Privacy Policy and consent to
              the limited data processing described therein. You acknowledge that Hunch processes only
              anonymised location coordinates and business type inputs, and that no personally identifiable
              information is required or requested.
            </Clause>

            <Clause number="6" title="Disclaimer of Warranties">
              Hunch is provided on an "as is" and "as available" basis. No warranty is made that the
              platform will be error-free, uninterrupted, or that prediction scores will be accurate for
              your specific business context. The developers make no representations about the completeness,
              reliability, or suitability of the platform for any particular purpose.
            </Clause>

            <Clause number="7" title="Limitation of Liability">
              To the fullest extent permitted by applicable Rwanda law, the developers of Hunch shall not
              be liable for any indirect, incidental, special, or consequential damages arising out of or
              in connection with your use of the platform, including but not limited to lost profits,
              business interruption, or loss of data, even if advised of the possibility of such damages.
            </Clause>

            <Clause number="8" title="Governing Law and Jurisdiction">
              This EULA is governed by and construed in accordance with the laws of the Republic of Rwanda.
              Any disputes arising under this agreement shall be subject to the exclusive jurisdiction of
              the courts of Rwanda. Rwanda Law N°058/2021 on the Protection of Personal Data and Privacy
              applies to all data processing activities associated with this platform.
            </Clause>

            <Clause number="9" title="Amendments">
              Hunch reserves the right to update this EULA at any time. Continued use of the platform
              following any update constitutes acceptance of the revised terms. Material changes will be
              indicated by updating the "Last updated" date at the top of this page.
            </Clause>

            <Clause number="10" title="Termination">
              This licence terminates automatically if you violate any of its terms. Upon termination, you
              must cease all use of the Hunch platform. The developers reserve the right to suspend or
              terminate access to the platform at any time and for any reason without prior notice.
            </Clause>

          </Section>

          <div className="bg-gray-50 border border-gray-200 rounded-xl p-4 mt-6 text-xs text-gray-500 text-center">
            <p>Hunch · African Leadership University Capstone Project · Kigali, Rwanda · 2026</p>
            <p className="mt-1">By continuing to use this platform, you accept this EULA and our Privacy Policy.</p>
          </div>
        </div>
      )}
    </div>
  )
}